// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart' as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3772456864099001323),
    name: 'AppUser',
    lastPropertyId: const obx_int.IdUid(9, 8998313979225501352),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(id: const obx_int.IdUid(1, 5293636612079901117), name: 'id', type: 6, flags: 1),
      obx_int.ModelProperty(id: const obx_int.IdUid(2, 6638355151059508031), name: 'userUuid', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(3, 2362688897217646211), name: 'phoneNumber', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(4, 397556645879112901), name: 'fullName', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(5, 898045710105087275), name: 'email', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(6, 8085992770549757188), name: 'profilePictureUrl', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(7, 4268088323301194849), name: 'isVerified', type: 1, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(8, 6388050552662158106), name: 'role', type: 9, flags: 0),
      obx_int.ModelProperty(id: const obx_int.IdUid(9, 8998313979225501352), name: 'createdAt', type: 10, flags: 0),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 3772456864099001323),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppUser: obx_int.EntityDefinition<AppUser>(
      model: _entities[0],
      toOneRelations: (AppUser object) => [],
      toManyRelations: (AppUser object) => {},
      getId: (AppUser object) => object.id,
      setId: (AppUser object, int id) {
        object.id = id;
      },
      objectToFB: (AppUser object, fb.Builder fbb) {
        final userUuidOffset = fbb.writeString(object.userUuid);
        final phoneNumberOffset = fbb.writeString(object.phoneNumber);
        final fullNameOffset = object.fullName == null ? null : fbb.writeString(object.fullName!);
        final emailOffset = object.email == null ? null : fbb.writeString(object.email!);
        final profilePictureUrlOffset = object.profilePictureUrl == null ? null : fbb.writeString(object.profilePictureUrl!);
        final roleOffset = fbb.writeString(object.role);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userUuidOffset);
        fbb.addOffset(2, phoneNumberOffset);
        fbb.addOffset(3, fullNameOffset);
        fbb.addOffset(4, emailOffset);
        fbb.addOffset(5, profilePictureUrlOffset);
        fbb.addBool(6, object.isVerified);
        fbb.addOffset(7, roleOffset);
        fbb.addInt64(8, object.createdAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 20);
        final idParam = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        final userUuidParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 6, '');
        final phoneNumberParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 8, '');
        final fullNameParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 10);
        final emailParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 12);
        final profilePictureUrlParam = const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 14);
        final isVerifiedParam = const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false);
        final roleParam = const fb.StringReader(asciiOptimization: true).vTableGet(buffer, rootOffset, 18, '');
        final createdAtParam = createdAtValue == null ? null : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final object = AppUser(
          id: idParam,
          userUuid: userUuidParam,
          phoneNumber: phoneNumberParam,
          fullName: fullNameParam,
          email: emailParam,
          profilePictureUrl: profilePictureUrlParam,
          isVerified: isVerifiedParam,
          role: roleParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppUser] entity fields to define ObjectBox queries.
class AppUser_ {
  /// See [AppUser.id].
  static final id = obx.QueryIntegerProperty<AppUser>(_entities[0].properties[0]);

  /// See [AppUser.userUuid].
  static final userUuid = obx.QueryStringProperty<AppUser>(_entities[0].properties[1]);

  /// See [AppUser.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<AppUser>(_entities[0].properties[2]);

  /// See [AppUser.fullName].
  static final fullName = obx.QueryStringProperty<AppUser>(_entities[0].properties[3]);

  /// See [AppUser.email].
  static final email = obx.QueryStringProperty<AppUser>(_entities[0].properties[4]);

  /// See [AppUser.profilePictureUrl].
  static final profilePictureUrl = obx.QueryStringProperty<AppUser>(_entities[0].properties[5]);

  /// See [AppUser.isVerified].
  static final isVerified = obx.QueryBooleanProperty<AppUser>(_entities[0].properties[6]);

  /// See [AppUser.role].
  static final role = obx.QueryStringProperty<AppUser>(_entities[0].properties[7]);

  /// See [AppUser.createdAt].
  static final createdAt = obx.QueryDateProperty<AppUser>(_entities[0].properties[8]);
}
