// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoMVMf7aQsWbh9t1UYgx7lAHVOO59gxrg',
    appId: '1:1096727737605:android:38a17a1456f05b62d6336c',
    messagingSenderId: '1096727737605',
    projectId: 'shipzy-37e1c',
    storageBucket: 'shipzy-37e1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl9eM-8jkOMbUKJ0HArBsu4k_kawxZhrM',
    appId: '1:1096727737605:ios:cd5ec8c1e44dac4dd6336c',
    messagingSenderId: '1096727737605',
    projectId: 'shipzy-37e1c',
    storageBucket: 'shipzy-37e1c.firebasestorage.app',
    androidClientId:
        '1096727737605-fl4c5pbqgb79h4q30q94nbic7niidhes.apps.googleusercontent.com',
    iosClientId:
        '1096727737605-nisqmrv9ghkmllcsqd1rprm3t5cnb840.apps.googleusercontent.com',
    iosBundleId: 'com.shipzy.shipzyDriver',
  );
}
