name: PR Checks

on:
    pull_request:
        branches: [main]

jobs:
    backend:
        uses: ./.github/workflows/backend-ci.yml
        secrets: inherit

    user-app:
        uses: ./.github/workflows/user-app-ci.yml
        secrets: inherit

    driver-app:
        uses: ./.github/workflows/driver-app-ci.yml
        secrets: inherit

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
        # Add linting steps if needed
